### ISSUE TITLE
Cannot Composing schemas more than 2 schemas

### ISSUE THREAD

**Issue by samnang** [dry-rb/dry-schema#307] opened 2020-08-04 15:23 UTC
**Describe the bug**

When I tried to compose schemas more than 2, then it doesn't support and throw me an error.

**To Reproduce**

```rb
require "dry-validation"

class UserContract < Dry::Validation::Contract 
  IndividualSchema = Dry::Schema.JSON do
    required(:first_name).filled(:str?)
    required(:last_name).filled(:str?)
  end

  CompanySchema = Dry::Schema.JSON do
    required(:name).filled(:str?)
    required(:owner_name).filled(:str?)
  end

  AnonymousSchema = Dry::Schema.JSON do
    required(:country).filled(:str?)
  end

  params do
    required(:details).schema(IndividualSchema | CompanySchema | AnonymousSchema)
  end
end

contract = UserContract.new

p contract.call(details: { first_name: "John", last_name: "Doe" }).success?
```

It raise an exception below:

```
dry-schema-1.5.2/lib/dry/schema/message/or.rb:16:in `map': undefined method `path' for #<Dry::Schema::Message::Or::MultiPath:0x00007fdceb290a7
0> (NoMethodError)
```

**Expected behavior**

I hope we should be able to compose more than 2 schemas.

**Your environment**

* Ruby version: ruby 2.7.1p83
* dry-schema: 1.5.2

**Comment by sirfilip** [comment] 2020-11-10 22:38
I think that this a duplicate of https://github.com/dry-rb/dry-schema/issues/277

**Comment by dugiahuy** [comment] 2021-01-07 06:59
We also have the same issue with our production application when tried to composing more than 2 schemas

**Closed** 2022-06-23 09:09 UTC
Labels: bug, help wanted
