### ISSUE TITLE
value([:integer, array[:integer]]) doesn't expand to (int? OR (array? AND each(int?)))

### ISSUE THREAD

**Issue by pabloh** [dry-rb/dry-schema#214] opened 2019-12-19 15:22 UTC
**Describe the bug**

When using typed arrays inside union types, the array's inner type predicate is not expanded.

**To Reproduce**

```ruby
schema = Dry::Schema.Params do
  required(:ids).value([:integer, array[:integer]])    
end  # rules={:ids=>"key?(:ids) AND key[ids](int? OR array?)"}

schema.call(ids: 3).success? # true
schema.call(ids: '3').success? # true
schema.call(ids: []).success? # true
schema.call(ids: [3]).success? # true
schema.call(ids: ['3']).success? # true
schema.call(ids: ['blah']).success? # true BUT SHOULD BE FALSE
```

A similar bug also happens when using `maybe` or `filled` instead of `value`: the type of the inner array elements are not properly checked.

**Your environment**

- Affects my production application: YES
- Ruby version: 2.6.5
- OS: Linux 4.10.0-42-generic #46-Ubuntu SMP x86_64 GNU/Linu

**Comment by pabloh** [comment] 2020-01-17 01:05
@solnic can you push this for `1.4.4`?

**Comment by solnic** [comment] 2020-01-17 08:16
@pabloh I updated the milestone. I'll get to this eventually but for now marking this as help-wanted.

**Comment by rawburt** [comment] 2020-02-16 18:52
@solnic It seems like the predicate inferrer should not return the same thing for these two different predicates https://github.com/dry-rb/dry-types/blob/master/spec/dry/types/predicate_inferrer_spec.rb#L19-L25 and perhaps https://github.com/dry-rb/dry-types/blob/master/spec/dry/types/predicate_inferrer_spec.rb#L24 is why the reported schema is failed on the array-of-integers check

**Comment by solnic** [comment] 2020-02-17 08:56
@rawburt yeah so the inferrer returns just a list of predicates that must be `AND`ed but it does not, on purpose, support complex types. These are handled [as special-cases in the DSL](https://github.com/dry-rb/dry-schema/blob/master/lib/dry/schema/macros/value.rb#L20-L21). The missing case is when you pass an array to `.value` like in this example, because it ends up as a sum type, with `right` being that array-of-integers, and the DSL misses this part.

**Comment by rawburt** [comment] 2020-02-18 05:32
@solnic`Value#call` receives `[[[:int?], [:array?]]]` as the `predicates` param and then [schema finder code](https://github.com/dry-rb/dry-schema/blob/master/lib/dry/schema/macros/value.rb#L14) does not find a `Processor`. Does this mean the bug is before `Value#call`?

**Comment by solnic** [comment] 2020-02-18 09:00
@rawburt yes. We have a method that [extracts type predicates](https://github.com/dry-rb/dry-schema/blob/50cc70b7b828c5ef754bf8326c1d05db49ff336c/lib/dry/schema/macros/dsl.rb#L213) and the problem is that inferring predicates doesn't support complex cases like this. I actually **just realized** that type spec handling can be greatly simplified and at the same time support more complex cases by just reusing `Value` API internally. I will give this a shot and report back.

**Closed** 2020-02-19 23:34 UTC
Labels: bug
